### PR TITLE
openbmc: srcrev bump ad8d54b743..4bcd6c002b (and its resulting related changes)

### LINKED ISSUE #77: Base toolchain fails to build with GCC 15.2.1
## Issue description

Arch Linux provides GCC `15.2.1 (20260204)` which is being used by `bitbake` to build the base toolchain.  
Due to re-declarations by GCC 15 for certain macros like `memchr`, the toolchain fails to build `m4-native` and other packages:

`m4-native`
```
| In file included from /usr/include/features.h:540,
|                  from /usr/include/errno.h:25,
|                  from ../../m4-1.4.20/lib/closeout.c:23:
| ./string.h:777:20: error: expected identifier or '(' before '_Generic'
|   777 | _GL_EXTERN_C void *memchr (const void *__s, int __c, size_t __n)
|       |                    ^~~~~~
| In file included from /usr/include/features.h:540,
|                  from /usr/include/bits/libc-header-start.h:33,
|                  from /usr/include/stdio.h:28,
|                  from ./stdio.h:55,
|                  from ../../m4-1.4.20/lib/clean-temp.h:26,
|                  from ../../m4-1.4.20/lib/clean-temp.c:22:
| ./stdlib.h:827:20: error: expected identifier or '(' before '_Generic'
|   827 | _GL_EXTERN_C void *bsearch (const void *__key,
|       |                    ^~~~~~~
| ./string.h:777:20: error: expected identifier or '(' before '_Generic'
|   777 | _GL_EXTERN_C void *memchr (const void *__s, int __c, size_t __n)
|       |                    ^~~~~~
| ./string.h:777:20: error: expected identifier or '(' before '_Generic'
|   777 | _GL_EXTERN_C void *memchr (const void *__s, int __c, size_t __n)
|       |                    ^~~~~~
| ./stdlib.h:827:20: error: expected identifier or '(' before '_Generic'
|   827 | _GL_EXTERN_C void *bsearch (const void *__key,
|       |                    ^~~~~~~
| ./stdlib.h:827:20: error: expected identifier or '(' before '_Generic'
|   827 | _GL_EXTERN_C void *bsearch (const void *__key,
|       |                    ^~~~~~~
| make[3]: *** [Makefile:4482: libm4_a-chdir-long.o] Error 1
| make[3]: *** [Makefile:4454: libm4_a-canonicalize.o] Error 1
| make[3]: *** [Makefile:4594: libm4_a-closeout.o] Error 1
| make[3]: *** [Makefile:4580: libm4_a-closein.o] Error 1
| make[3]: *** [Makefile:4510: libm4_a-clean-temp-simple.o] Error 1
| make[3]: Leaving directory '/home/tan/git/github.com/canopybmc/canopybmc/build/hpe-proliant-g11/tmp/work/x86_64-linux/m4-native/1.4.20/build/lib'
| make[3]: *** [Makefile:4496: libm4_a-clean-temp.o] Error 1
| make[2]: *** [Makefile:3608: all] Error 2
| make[2]: Leaving directory '/home/tan/git/github.com/canopybmc/canopybmc/build/hpe-proliant-g11/tmp/work/x86_64-linux/m4-native/1.4.20/build/lib'
| make[1]: *** [Makefile:2530: all-recursive] Error 1
| make[1]: Leaving directory '/home/tan/git/github.com/canopybmc/canopybmc/build/hpe-proliant-g11/tmp/work/x86_64-linux/m4-native/1.4.20/build'
```

`libfdt`
```
| [2/12] gcc -Ilibfdt/libfdt.so.1.7.2.p -Ilibfdt -I../git/libfdt -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -Wpointer-arith -Wcast-qual -Wnested-externs -Wstrict-prototypes -Wmissing-prototypes -Wredundant-decls -Wshadow -Wsuggest-attribute=format -Wwrite-strings -DFDT_ASSUME_MASK=0 -DNO_YAML -DNO_VALGRIND -isystem/home/tan/git/github.com/canopybmc/canopybmc/build/hpe-proliant-g11/tmp/work/x86_64-linux/dtc-native/1.7.2/recipe-sysroot-native/usr/include -O2 -pipe -fPIC -MD -MQ libfdt/libfdt.so.1.7.2.p/fdt_overlay.c.o -MF libfdt/libfdt.so.1.7.2.p/fdt_overlay.c.o.d -o libfdt/libfdt.so.1.7.2.p/fdt_overlay.c.o -c ../git/libfdt/fdt_overlay.c
| FAILED: libfdt/libfdt.so.1.7.2.p/fdt_overlay.c.o
| gcc -Ilibfdt/libfdt.so.1.7.2.p -Ilibfdt -I../git/libfdt -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -Wpointer-arith -Wcast-qual -Wnested-externs -Wstrict-prototypes -Wmissing-prototypes -Wredundant-decls -Wshadow -Wsuggest-attribute=format -Wwrite-strings -DFDT_ASSUME_MASK=0 -DNO_YAML -DNO_VALGRIND -isystem/home/tan/git/github.com/canopybmc/canopybmc/build/hpe-proliant-g11/tmp/work/x86_64-linux/dtc-native/1.7.2/recipe-sysroot-native/usr/include -O2 -pipe -fPIC -MD -MQ libfdt/libfdt.so.1.7.2.p/fdt_overlay.c.o -MF libfdt/libfdt.so.1.7.2.p/fdt_overlay.c.o.d -o libfdt/libfdt.so.1.7.2.p/fdt_overlay.c.o -c ../git/libfdt/fdt_overlay.c
| ../git/libfdt/fdt_overlay.c: In function ‘overlay_fixup_phandle’:
| ../git/libfdt/fdt_overlay.c:424:21: error: assignment discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
|   424 |                 sep = memchr(fixup_str, ':', fixup_len);
|       |                     ^
| ../git/libfdt/fdt_overlay.c:434:21: error: assignment discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
|   434 |                 sep = memchr(name, ':', fixup_len);
|       |                     ^
| cc1: all warnings being treated as errors
| [3/12] gcc -Ifdtput.p -I. -I../git -Ilibfdt -I../git/libfdt -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -Wpointer-arith -Wcast-qual -Wnested-externs -Wstrict-prototypes -Wmissing-prototypes -Wredundant-decls -Wshadow -Wsuggest-attribute=format -Wwrite-strings -DFDT_ASSUME_MASK=0 -DNO_YAML -DNO_VALGRIND -isystem/home/tan/git/github.com/canopybmc/canopybmc/build/hpe-proliant-g11/tmp/work/x86_64-linux/dtc-native/1.7.2/recipe-sysroot-native/usr/include -O2 -pipe -MD -MQ fdtput.p/fdtput.c.o -MF fdtput.p/fdtput.c.o.d -o fdtput.p/fdtput.c.o -c ../git/fdtput.c
| FAILED: fdtput.p/fdtput.c.o
| gcc -Ifdtput.p -I. -I../git -Ilibfdt -I../git/libfdt -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -Wpointer-arith -Wcast-qual -Wnested-externs -Wstrict-prototypes -Wmissing-prototypes -Wredundant-decls -Wshadow -Wsuggest-attribute=format -Wwrite-strings -DFDT_ASSUME_MASK=0 -DNO_YAML -DNO_VALGRIND -isystem/home/tan/git/github.com/canopybmc/canopybmc/build/hpe-proliant-g11/tmp/work/x86_64-linux/dtc-native/1.7.2/recipe-sysroot-native/usr/include -O2 -pipe -MD -MQ fdtput.p/fdtput.c.o -MF fdtput.p/fdtput.c.o.d -o fdtput.p/fdtput.c.o -c ../git/fdtput.c
| ../git/fdtput.c: In function ‘create_node’:
| ../git/fdtput.c:235:11: error: assignment discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
|   235 |         p = strrchr(node_name, '/');
|       |           ^
```

## Expected behaviour

It builds with GCC 15.

## Current behaviour

Even with a hot-fix to guard the macros (thanks @sylv-io for quickly providing one) in `m4-native` from re-definition, the build fails on other recipes like `util-linux` / `libfdt` due to `discarded-qualifiers` (see the description).

## Workaround

I've set up a Docker image with Ubuntu 24.04 LTS on my Hydra instance to have GCC 14 and Python 3.12 which allows building an image.

GCC14 from AUR does **not** help.

## Build environment

```
Host: Hydra
OS: Arch Linux
Python: 3.13.12 (from AUR, loaded via virtualenv)
GCC:
  gcc 15.2.1+r604+g0b99615a8aef-1
  gcc-libs 15.2.1+r604+g0b99615a8aef-1
  libgcc 15.2.1+r604+g0b99615a8aef-1
```

### PR DESCRIPTION
**Pull request by sinuscosinustan**
Bump the OpenBMC reference to commit 4bcd6c002b, which also updates Yocto to `wrynose`.

- Pulls in upstream changes across multiple platforms and recipes for the `wrynose` Yocto release.
- Patches refreshed to apply cleanly on top of the new upstream base.
- Fixed source directory assignments: `wrynose` now requires sources to reside in `UNPACKDIR` instead of `WORKDIR`; git-sourced recipes no longer support re-assigning `S`.
- The FIT image generation moved from a custom implementation to the upstream `linux-yocto-fitimage` recipe following recent Yocto recipe updates.
- The GXP validates the U-Boot signature stored in a separate `uboot-sig` partition. If this partition is not updated alongside U-Boot, SRoT validation fails and the iLO bricks. The `uboot-sig` image is now included in `static.mtd.tar` and declared as an optional image in `phosphor-bmc-code-mgmt`.
- **IMPORTANT**: A one-time update using `static.mtd.all.tar` is required when applying this change from an older build, as the previous code does not copy `uboot-sig` to the initramfs. Using `static.mtd.tar` before this commit is applied will brick the iLO.
- Upstream webui-vue migrated from Vue-CLI to Vite. `NODE_ENV` is deprecated in Vite; the dotenv file is now copied to `.env.production` to restore working theme/gzip compression.
- Removed the dumps-page fix patch, which was merged upstream as `5c4f461`.
- Added a `go-task` helper to automate future OpenBMC srcrev bumps.

### CODE REVIEW

**Comment by mynetz** [comment]
@sinuscosinustan can you check if your changes will touch canopybmc/canopybmc#151. If yes, can you add "Solves #xyz" to this PR?

**Comment by sinuscosinustan** [comment]
still need to fix the missing `uboot-sig` image in the update tarball (otherwise we end up with bricked BMCs)

**Comment by sinuscosinustan** [comment]
@mynetz This PR only partially solves the issue. The FIT image now includes the signature, but we till don't validate it in U-Boot.

**Comment by walterchris** [comment]
Is the failing User: Authentication Configuration Test a regression? Does upstream not serve this endpoint anymore? Same goes for the LDAP/ActiveDirectory endpoints.

I mean we don't support this (yet) but normally at least the endpoints exist.

**Comment by sinuscosinustan** [comment]
> Is the failing User: Authentication Configuration Test a regression? Does upstream not serve this endpoint anymore? Same goes for the LDAP/ActiveDirectory endpoints.
> 
> I mean we don't support this (yet) but normally at least the endpoints exist.

Found the issue @walterchris . The root user is actually being deleted, though it returns 404. Investigating and preparing an upstream fix

**Comment by sinuscosinustan** [comment]
Moved the bmcweb-related issue to #157. This issue should not interfere with the rebase.

**Review by walterchris — APPROVED** [review]
I like the Taskfile approach.
